import{a as S,S as L,i as d}from"./assets/vendor-DQq26VV5.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))r(o);new MutationObserver(o=>{for(const l of o)if(l.type==="childList")for(const a of l.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function n(o){const l={};return o.integrity&&(l.integrity=o.integrity),o.referrerPolicy&&(l.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?l.credentials="include":o.crossOrigin==="anonymous"?l.credentials="omit":l.credentials="same-origin",l}function r(o){if(o.ep)return;o.ep=!0;const l=n(o);fetch(o.href,l)}})();async function f(e,t){try{const r=await S.get("https://pixabay.com/api/",{params:{key:"53361470-387588d6f5d48c87f9e06e518",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}});return{images:r.data.hits,total:r.data.totalHits}}catch(r){throw r}}let s;function y(e){let t=document.querySelector(".gallery");t===null&&(document.querySelector(".container").insertAdjacentHTML("afterend",'<ul class="gallery"></ul>'),t=document.querySelector(".gallery"));const n=e.map(r=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${r.largeImageURL}">
                <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
            </a>
            <div class="info">
                <p class="gallery-info-item">Likes <span>${r.likes}</span></p>
                <p class="gallery-info-item">Views <span>${r.views}</span></p>
                <p class="gallery-info-item">Comments <span>${r.comments}</span></p>
                <p class="gallery-info-item">Downloads <span>${r.downloads}</span></p>
            </div>
        </li>`).join("");s===void 0&&(s=new L(".gallery a",{captionsData:"alt",captionDelay:250})),t.insertAdjacentHTML("beforeend",n),s.refresh()}function b(){const e=document.querySelector(".gallery");e.innerHTML=""}function m(){let e=document.querySelector(".loader");e===null&&(document.querySelector(".container").insertAdjacentHTML("beforeend",'<span class="loader visually-hidden"></span>'),e=document.querySelector(".loader")),e.classList.remove("visually-hidden")}function p(){document.querySelector(".loader").classList.add("visually-hidden")}function h(){let e=document.querySelector(".btn-fetch");e===null&&(document.querySelector(".container").insertAdjacentHTML("beforeend",'<button class="btn-fetch visually-hidden">Load More</button>'),e=document.querySelector(".btn-fetch")),e.classList.remove("visually-hidden")}function v(){const e=document.querySelector(".btn-fetch");if(e===null){console.error("THERE ARE NO SENSE TO HIDE SOMETHING THAT DOES NOT EXIST");return}e.classList.add("visually-hidden")}function q(){let t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}let i=1,g;const c=document.querySelector(".form"),u=document.querySelector(".form-input"),w=document.querySelector(".btn-fetch");w.addEventListener("click",async()=>{let e;v(),m();try{const t=await f(g,++i);e=t.total,y(t.images),q()}catch(t){console.error("Error fetching images:",t)}finally{if(p(),e===void 0){console.error("Error during extract total");return}i*15<e?h():d.info({title:"We're sorry, but you've reached the end of search results",position:"topRight"})}});c.addEventListener("submit",async e=>{e.preventDefault(),i=1;let t;if(u.value.trim()===""){d.error({title:"To be honest, i wish you will be in hell if you think that empty field is funny",position:"topRight"}),c.reset();return}g=u.value,b(),m();try{const n=await f(u.value,i);t=n.total,!n||n.images.length===0?d.error({title:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(y(n.images),i*15<t&&h(),c.reset())}catch(n){console.error("Error fetching images:",n)}finally{p()}});
//# sourceMappingURL=index.js.map
