import{a as b,S as L,i as a}from"./assets/vendor-DQq26VV5.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))r(n);new MutationObserver(n=>{for(const l of n)if(l.type==="childList")for(const s of l.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&r(s)}).observe(document,{childList:!0,subtree:!0});function o(n){const l={};return n.integrity&&(l.integrity=n.integrity),n.referrerPolicy&&(l.referrerPolicy=n.referrerPolicy),n.crossOrigin==="use-credentials"?l.credentials="include":n.crossOrigin==="anonymous"?l.credentials="omit":l.credentials="same-origin",l}function r(n){if(n.ep)return;n.ep=!0;const l=o(n);fetch(n.href,l)}})();async function f(e,t){try{const r=await b.get("https://pixabay.com/api/",{params:{key:"53361470-387588d6f5d48c87f9e06e518",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}});return{images:r.data.hits,total:r.data.totalHits}}catch(r){throw r}}let c;function y(e){let t=document.querySelector(".gallery");t===null&&(document.querySelector(".container").insertAdjacentHTML("afterend",'<ul class="gallery"></ul>'),t=document.querySelector(".gallery"));const o=e.map(r=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${r.largeImageURL}">
                <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
            </a>
            <div class="info">
                <p class="gallery-info-item">Likes <span>${r.likes}</span></p>
                <p class="gallery-info-item">Views <span>${r.views}</span></p>
                <p class="gallery-info-item">Comments <span>${r.comments}</span></p>
                <p class="gallery-info-item">Downloads <span>${r.downloads}</span></p>
            </div>
        </li>`).join("");c===void 0&&(c=new L(".gallery a",{captionsData:"alt",captionDelay:250})),t.insertAdjacentHTML("beforeend",o),c.refresh()}function v(){const e=document.querySelector(".gallery");e.innerHTML=""}function h(){let e=document.querySelector(".loader");e===null&&(document.querySelector(".container").insertAdjacentHTML("beforeend",'<span class="loader visually-hidden"></span>'),e=document.querySelector(".loader")),e.classList.remove("visually-hidden")}function m(){document.querySelector(".loader").classList.add("visually-hidden")}function p(){let e=document.querySelector(".btn-fetch");e===null&&(document.querySelector(".container").insertAdjacentHTML("beforeend",'<button class="btn-fetch visually-hidden">Load More</button>'),e=document.querySelector(".btn-fetch")),e.classList.remove("visually-hidden")}function g(){let e=document.querySelector(".btn-fetch");e===null&&(document.querySelector(".container").insertAdjacentHTML("beforeend",'<button class="btn-fetch">Load More</button>'),e=document.querySelector(".btn-fetch")),e.classList.add("visually-hidden")}let i=1,S;const u=document.querySelector(".form"),d=document.querySelector(".form-input"),q=document.querySelector(".btn-fetch");q.addEventListener("click",async()=>{let e;g(),h();try{const t=await f(S,++i);e=t.total,y(t.images);const o=document.querySelector(".gallery-item");if(o){const r=o.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}catch(t){console.error("Error fetching images:",t)}finally{if(m(),e===void 0){console.error("Error during extract total");return}i*15<e?p():a.info({title:"We're sorry, but you've reached the end of search results",position:"topRight"})}});u.addEventListener("submit",async e=>{e.preventDefault(),g(),i=1;let t;if(d.value.trim()===""){a.error({title:"To be honest, i wish you will be in hell if you think that empty field is funny",position:"topRight"}),u.reset();return}S=d.value,v(),h();try{const o=await f(d.value,i);t=o.total,!o||o.images.length===0?a.error({title:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(y(o.images),i*15<t?p():a.info({title:"We're sorry, but you've reached the end of search results",position:"topRight"}),u.reset())}catch(o){console.error("Error fetching images:",o)}finally{m()}});
//# sourceMappingURL=index.js.map
