import{a as S,S as L,i as d}from"./assets/vendor-DQq26VV5.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))r(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const s of n.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&r(s)}).observe(document,{childList:!0,subtree:!0});function a(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function r(o){if(o.ep)return;o.ep=!0;const n=a(o);fetch(o.href,n)}})();async function y(e,t){try{const r=await S.get("https://pixabay.com/api/",{params:{key:"53361470-387588d6f5d48c87f9e06e518",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}});return{images:r.data.hits,total:r.data.totalHits}}catch(r){throw r}}let i;function f(e){let t=document.querySelector(".gallery");t===null&&(document.querySelector(".container").insertAdjacentHTML("afterend",'<ul class="gallery"></ul>'),t=document.querySelector(".gallery"));const a=e.map(r=>`
        <li class="gallery-item">
            <a class="gallery-link" href="${r.largeImageURL}">
                <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
            </a>
            <div class="info">
                <p class="gallery-info-item">Likes <span>${r.likes}</span></p>
                <p class="gallery-info-item">Views <span>${r.views}</span></p>
                <p class="gallery-info-item">Comments <span>${r.comments}</span></p>
                <p class="gallery-info-item">Downloads <span>${r.downloads}</span></p>
            </div>
        </li>`).join("");i===void 0&&(i=new L(".gallery a",{captionsData:"alt",captionDelay:250})),t.insertAdjacentHTML("beforeend",a),i.refresh()}function v(){const e=document.querySelector(".gallery");e.innerHTML=""}function m(){let e=document.querySelector(".loader");e===null&&(document.querySelector(".container").insertAdjacentHTML("beforeend",'<span class="loader visually-hidden"></span>'),e=document.querySelector(".loader")),e.classList.remove("visually-hidden")}function g(){document.querySelector(".loader").classList.add("visually-hidden")}function p(){const e=document.querySelector(".btn-fetch");e===null&&document.querySelector(".container").insertAdjacentHTML("beforeend",'<button class="btn-fetch visually-hidden">Load More</button>'),e.classList.remove("visually-hidden")}function b(){document.querySelector(".btn-fetch").classList.add("visually-hidden")}let l=1,h;const c=document.querySelector(".form"),u=document.querySelector(".form-input"),q=document.querySelector(".btn-fetch");q.addEventListener("click",async()=>{let e;b(),m();try{const t=await y(h,++l);e=t.total,f(t.images)}catch(t){console.error("Error fetching images:",t)}finally{if(g(),console.log(e),e===void 0){console.error("Error during extract total");return}l*15<e?p():d.info({title:"We're sorry, but you've reached the end of search results",position:"topRight"})}});c.addEventListener("submit",async e=>{if(e.preventDefault(),l=1,u.value.trim()===""){d.error({title:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),c.reset();return}h=u.value,v(),m();try{const t=await y(u.value,l);!t||t.images.length===0?d.error({title:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(f(t.images),p());let r=document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}catch(t){console.error("Error fetching images:",t)}finally{g(),c.reset()}});
//# sourceMappingURL=index.js.map
